---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: maven
    script: |-
      #!/bin/bash
      mvn -B package -DskipTests
- name: Smoke-Test
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -p target/hellorest.war
  - name: Test
    type: tester
    script: |-
      #!/bin/bash
      mvn test -Durl="http://hellorest-int.mybluemix.net/"
    enable_tests: true
    test_file_pattern: tests/TEST-*.xml
